/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WallRouteImport } from './routes/wall'
import { Route as StoriesRouteImport } from './routes/stories'
import { Route as LogRouteImport } from './routes/log'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as GroupsRouteImport } from './routes/groups'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StoriesIndexRouteImport } from './routes/stories.index'
import { Route as GroupsIndexRouteImport } from './routes/groups.index'
import { Route as StoriesSubmitRouteImport } from './routes/stories.submit'
import { Route as GroupsNewRouteImport } from './routes/groups.new'
import { Route as GroupsJoinRouteImport } from './routes/groups.join'
import { Route as GroupsSlugRouteImport } from './routes/groups.$slug'

const WallRoute = WallRouteImport.update({
  id: '/wall',
  path: '/wall',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesRoute = StoriesRouteImport.update({
  id: '/stories',
  path: '/stories',
  getParentRoute: () => rootRouteImport,
} as any)
const LogRoute = LogRouteImport.update({
  id: '/log',
  path: '/log',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsRoute = GroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesIndexRoute = StoriesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StoriesRoute,
} as any)
const GroupsIndexRoute = GroupsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GroupsRoute,
} as any)
const StoriesSubmitRoute = StoriesSubmitRouteImport.update({
  id: '/submit',
  path: '/submit',
  getParentRoute: () => StoriesRoute,
} as any)
const GroupsNewRoute = GroupsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => GroupsRoute,
} as any)
const GroupsJoinRoute = GroupsJoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => GroupsRoute,
} as any)
const GroupsSlugRoute = GroupsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => GroupsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/community': typeof CommunityRoute
  '/demo': typeof DemoRoute
  '/groups': typeof GroupsRouteWithChildren
  '/history': typeof HistoryRoute
  '/log': typeof LogRoute
  '/stories': typeof StoriesRouteWithChildren
  '/wall': typeof WallRoute
  '/groups/$slug': typeof GroupsSlugRoute
  '/groups/join': typeof GroupsJoinRoute
  '/groups/new': typeof GroupsNewRoute
  '/stories/submit': typeof StoriesSubmitRoute
  '/groups/': typeof GroupsIndexRoute
  '/stories/': typeof StoriesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/community': typeof CommunityRoute
  '/demo': typeof DemoRoute
  '/history': typeof HistoryRoute
  '/log': typeof LogRoute
  '/wall': typeof WallRoute
  '/groups/$slug': typeof GroupsSlugRoute
  '/groups/join': typeof GroupsJoinRoute
  '/groups/new': typeof GroupsNewRoute
  '/stories/submit': typeof StoriesSubmitRoute
  '/groups': typeof GroupsIndexRoute
  '/stories': typeof StoriesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/community': typeof CommunityRoute
  '/demo': typeof DemoRoute
  '/groups': typeof GroupsRouteWithChildren
  '/history': typeof HistoryRoute
  '/log': typeof LogRoute
  '/stories': typeof StoriesRouteWithChildren
  '/wall': typeof WallRoute
  '/groups/$slug': typeof GroupsSlugRoute
  '/groups/join': typeof GroupsJoinRoute
  '/groups/new': typeof GroupsNewRoute
  '/stories/submit': typeof StoriesSubmitRoute
  '/groups/': typeof GroupsIndexRoute
  '/stories/': typeof StoriesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/community'
    | '/demo'
    | '/groups'
    | '/history'
    | '/log'
    | '/stories'
    | '/wall'
    | '/groups/$slug'
    | '/groups/join'
    | '/groups/new'
    | '/stories/submit'
    | '/groups/'
    | '/stories/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/community'
    | '/demo'
    | '/history'
    | '/log'
    | '/wall'
    | '/groups/$slug'
    | '/groups/join'
    | '/groups/new'
    | '/stories/submit'
    | '/groups'
    | '/stories'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/community'
    | '/demo'
    | '/groups'
    | '/history'
    | '/log'
    | '/stories'
    | '/wall'
    | '/groups/$slug'
    | '/groups/join'
    | '/groups/new'
    | '/stories/submit'
    | '/groups/'
    | '/stories/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  CommunityRoute: typeof CommunityRoute
  DemoRoute: typeof DemoRoute
  GroupsRoute: typeof GroupsRouteWithChildren
  HistoryRoute: typeof HistoryRoute
  LogRoute: typeof LogRoute
  StoriesRoute: typeof StoriesRouteWithChildren
  WallRoute: typeof WallRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wall': {
      id: '/wall'
      path: '/wall'
      fullPath: '/wall'
      preLoaderRoute: typeof WallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories': {
      id: '/stories'
      path: '/stories'
      fullPath: '/stories'
      preLoaderRoute: typeof StoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/log': {
      id: '/log'
      path: '/log'
      fullPath: '/log'
      preLoaderRoute: typeof LogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups': {
      id: '/groups'
      path: '/groups'
      fullPath: '/groups'
      preLoaderRoute: typeof GroupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories/': {
      id: '/stories/'
      path: '/'
      fullPath: '/stories/'
      preLoaderRoute: typeof StoriesIndexRouteImport
      parentRoute: typeof StoriesRoute
    }
    '/groups/': {
      id: '/groups/'
      path: '/'
      fullPath: '/groups/'
      preLoaderRoute: typeof GroupsIndexRouteImport
      parentRoute: typeof GroupsRoute
    }
    '/stories/submit': {
      id: '/stories/submit'
      path: '/submit'
      fullPath: '/stories/submit'
      preLoaderRoute: typeof StoriesSubmitRouteImport
      parentRoute: typeof StoriesRoute
    }
    '/groups/new': {
      id: '/groups/new'
      path: '/new'
      fullPath: '/groups/new'
      preLoaderRoute: typeof GroupsNewRouteImport
      parentRoute: typeof GroupsRoute
    }
    '/groups/join': {
      id: '/groups/join'
      path: '/join'
      fullPath: '/groups/join'
      preLoaderRoute: typeof GroupsJoinRouteImport
      parentRoute: typeof GroupsRoute
    }
    '/groups/$slug': {
      id: '/groups/$slug'
      path: '/$slug'
      fullPath: '/groups/$slug'
      preLoaderRoute: typeof GroupsSlugRouteImport
      parentRoute: typeof GroupsRoute
    }
  }
}

interface GroupsRouteChildren {
  GroupsSlugRoute: typeof GroupsSlugRoute
  GroupsJoinRoute: typeof GroupsJoinRoute
  GroupsNewRoute: typeof GroupsNewRoute
  GroupsIndexRoute: typeof GroupsIndexRoute
}

const GroupsRouteChildren: GroupsRouteChildren = {
  GroupsSlugRoute: GroupsSlugRoute,
  GroupsJoinRoute: GroupsJoinRoute,
  GroupsNewRoute: GroupsNewRoute,
  GroupsIndexRoute: GroupsIndexRoute,
}

const GroupsRouteWithChildren =
  GroupsRoute._addFileChildren(GroupsRouteChildren)

interface StoriesRouteChildren {
  StoriesSubmitRoute: typeof StoriesSubmitRoute
  StoriesIndexRoute: typeof StoriesIndexRoute
}

const StoriesRouteChildren: StoriesRouteChildren = {
  StoriesSubmitRoute: StoriesSubmitRoute,
  StoriesIndexRoute: StoriesIndexRoute,
}

const StoriesRouteWithChildren =
  StoriesRoute._addFileChildren(StoriesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  CommunityRoute: CommunityRoute,
  DemoRoute: DemoRoute,
  GroupsRoute: GroupsRouteWithChildren,
  HistoryRoute: HistoryRoute,
  LogRoute: LogRoute,
  StoriesRoute: StoriesRouteWithChildren,
  WallRoute: WallRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
